"""CSV roster import for school identities and GitHub accounts."""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping

from autograde.domain import Repository
from autograde.state import StateStore


class RosterError(ValueError):
    """The roster cannot be mapped to repositories without ambiguity."""


@dataclass(frozen=True, slots=True)
class RosterEntry:
    student_key: str
    github_id: str
    github_repository_id: int | None = None
    repository_name: str | None = None
    clone_url: str | None = None
    target_ref: str | None = None


def read_roster(path: str | Path) -> tuple[RosterEntry, ...]:
    """Read a UTF-8 CSV roster.

    Only ``student_key`` and ``github_id`` are required. Optional columns let an
    instructor override values discovered or generated by repository policy.
    """

    roster_path = Path(path)
    try:
        handle = roster_path.open("r", encoding="utf-8-sig", newline="")
    except OSError as exc:
        raise RosterError(f"cannot read roster: {roster_path}") from exc

    with handle:
        reader = csv.DictReader(handle)
        fields = set(reader.fieldnames or ())
        missing = {"student_key", "github_id"} - fields
        if missing:
            names = ", ".join(sorted(missing))
            raise RosterError(f"roster is missing required column(s): {names}")

        entries: list[RosterEntry] = []
        seen_students: dict[str, int] = {}
        seen_github_ids: dict[str, int] = {}
        for line_number, row in enumerate(reader, start=2):
            student_key = _required(row, "student_key", line_number)
            github_id = _required(row, "github_id", line_number)
            if student_key in seen_students:
                raise RosterError(
                    f"line {line_number}: duplicate student_key {student_key!r} "
                    f"(first seen on line {seen_students[student_key]})"
                )
            normalized_github_id = github_id.casefold()
            if normalized_github_id in seen_github_ids:
                raise RosterError(
                    f"line {line_number}: duplicate github_id {github_id!r} "
                    f"(first seen on line {seen_github_ids[normalized_github_id]})"
                )
            seen_students[student_key] = line_number
            seen_github_ids[normalized_github_id] = line_number
            raw_repository_id = _optional(row, "github_repository_id")
            if raw_repository_id is None:
                repository_id = None
            else:
                try:
                    repository_id = int(raw_repository_id)
                except ValueError as exc:
                    raise RosterError(
                        f"line {line_number}: github_repository_id must be an integer"
                    ) from exc
                if repository_id <= 0:
                    raise RosterError(
                        f"line {line_number}: github_repository_id must be positive"
                    )

            entries.append(
                RosterEntry(
                    student_key=student_key,
                    github_id=github_id,
                    github_repository_id=repository_id,
                    repository_name=_optional(row, "repository_name"),
                    clone_url=_optional(row, "clone_url"),
                    target_ref=_optional(row, "target_ref"),
                )
            )

    if not entries:
        raise RosterError("roster contains no students")
    return tuple(entries)


def import_roster(
    store: StateStore,
    entries: Iterable[RosterEntry],
    *,
    organization: str,
    repository_template: str = "{github_id}",
    clone_url_template: str = "https://github.com/{organization}/{repository_name}.git",
    target_ref: str = "main",
) -> tuple[Repository, ...]:
    """Map roster identities to repository records and upsert them atomically per row."""

    organization = organization.strip()
    if not organization:
        raise RosterError("organization must not be empty")

    normalized_entries = tuple(entries)
    seen_keys: set[str] = set()
    seen_students: set[str] = set()
    seen_github_ids: set[str] = set()
    plans: list[tuple[RosterEntry, str, str, str, str, str]] = []
    for entry in normalized_entries:
        student_key = entry.student_key.strip()
        github_id = entry.github_id.strip()
        if not student_key or not github_id:
            raise RosterError("student_key and github_id must not be empty")
        if student_key in seen_students:
            raise RosterError(f"duplicate student_key: {student_key!r}")
        normalized_github_id = github_id.casefold()
        if normalized_github_id in seen_github_ids:
            raise RosterError(f"duplicate github_id: {github_id!r}")
        seen_students.add(student_key)
        seen_github_ids.add(normalized_github_id)
        base_context = {
            "organization": organization,
            "student_key": student_key,
            "github_id": github_id,
        }
        repository_name = entry.repository_name or _format_template(
            repository_template, base_context, "repository_template"
        )
        repository_name = repository_name.strip()
        if not repository_name:
            raise RosterError(
                f"repository name is empty for student {entry.student_key!r}"
            )

        context = {**base_context, "repository_name": repository_name}
        clone_url = entry.clone_url or _format_template(
            clone_url_template, context, "clone_url_template"
        )
        repository_key = f"{organization}/{repository_name}"
        if repository_key in seen_keys:
            raise RosterError(f"duplicate repository mapping: {repository_key}")
        seen_keys.add(repository_key)
        plans.append(
            (
                entry,
                student_key,
                github_id,
                repository_name,
                clone_url,
                repository_key,
            )
        )

    return store.upsert_repositories(
        {
            "repository_key": repository_key,
            "student_key": student_key,
            "github_repository_id": entry.github_repository_id,
            "owner": organization,
            "name": repository_name,
            "clone_url": clone_url,
            "target_ref": entry.target_ref or target_ref,
            "metadata": {"github_id": github_id},
        }
        for (
            entry,
            student_key,
            github_id,
            repository_name,
            clone_url,
            repository_key,
        ) in plans
    )


def _required(row: Mapping[str, str | None], field: str, line_number: int) -> str:
    value = _optional(row, field)
    if value is None:
        raise RosterError(f"line {line_number}: {field} must not be empty")
    return value


def _optional(row: Mapping[str, str | None], field: str) -> str | None:
    value = row.get(field)
    if value is None:
        return None
    stripped = value.strip()
    return stripped or None


def _format_template(template: str, context: Mapping[str, str], label: str) -> str:
    try:
        return template.format_map(context)
    except (KeyError, ValueError) as exc:
        raise RosterError(f"invalid {label}: {exc}") from exc


__all__ = ["RosterEntry", "RosterError", "import_roster", "read_roster"]
